import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight } from "lucide-react";
import { SiteHeader } from "@/components/site/header";
import { SiteFooter } from "@/components/site/footer";
import { collections } from "@/lib/data/catalog";

const images = ["/images/collection_sarees_1785319884762.png", "/images/collection_jewelry_1785319899305.png", "/images/collection_lehengas_1785319969542.png", "/images/saree_editorial_1785319869961.png"];
export default function CollectionsPage() { return <><SiteHeader /><main className="bg-[#f7f4ed] pt-28 text-[#171310] dark:bg-[#171310] dark:text-[#f7f4ed]"><section className="mx-auto max-w-[1480px] px-5 pb-[clamp(6rem,10vw,10rem)] pt-10 md:px-8 xl:px-10"><p className="text-[9px] font-semibold uppercase tracking-[0.3em] text-[#b98a3d]">House narratives</p><h1 className="mt-5 max-w-[11ch] font-serif text-[clamp(4.5rem,10vw,10rem)] font-light leading-[0.78] tracking-[-0.05em]">Collections with a point of view.</h1><p className="mt-9 max-w-md text-base leading-7 text-[#716b63] dark:text-[#eee9de]/55">Seasonal stories and permanent signatures, composed as complete wardrobes.</p><div className="mt-[clamp(5rem,10vw,9rem)] space-y-5">{collections.map((collection,index)=><Link key={collection.id} href={`/collections/${collection.slug}`} className="group grid gap-5 border-t border-[#281e16]/12 pt-5 md:grid-cols-[0.7fr_1fr_0.8fr] md:items-center dark:border-white/12"><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-[#b98a3d]">0{index+1} · {collection.season}</p><div className="relative aspect-[16/8] overflow-hidden rounded-[20px]"><Image src={images[index%images.length]} alt={collection.title} fill className="object-cover transition-transform duration-[1000ms] ease-[cubic-bezier(.16,1,.3,1)] group-hover:scale-[1.03]" sizes="50vw" /></div><div className="flex items-end justify-between gap-4 py-4"><div><h2 className="font-serif text-[clamp(2.6rem,5vw,5.5rem)] font-light leading-[0.88] tracking-[-0.04em]">{collection.title}</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#716b63] dark:text-[#eee9de]/48">{collection.description}</p></div><ArrowDownRight className="h-5 w-5 shrink-0 text-[#b98a3d]" /></div></Link>)}</div></section></main><SiteFooter /></>; }
